### ISSUE TITLE
RcisTarget for region enrichment

### ISSUE THREAD

**Issue by qingnanl** [aertslab/RcisTarget#16]
Dear Developers,

Thanks for making this great package. I would like to ask whether this package can also take gemonic regions as input for motif enrichment. It would be extremely helpful in comparing gene set enrichment and ATAC-seq peak enrichment.

Thanks,

qingnanl

**Comment by s-aibar** [comment]
Dear @qingnanl ,

Yes, you can use either genes or genomic regions as input for RcisTarget.
