### ISSUE TITLE
Error in .RcisTarget_calcAUC(geneSets = geneSets, rankings = rankings, 

### ISSUE THREAD

**Issue by rbenel** [aertslab/RcisTarget#17]
Hi, 
I receive this warning when running the `calcAUC` function.

`Fewer than 80% of the genes/features in the gene-sets are included in the rankings.Check wether the IDs in the 'rankings' (columns) and 'geneSets' match.`

I am using a character vector of gene names as my input, so I can't figure out what the issue is. 
`> head(Cluster[[4]])`
`[1]  "MDS2"   "FTX"  "SIX3-AS1"  "FOXCUT"  "DIO3OS" `

If I use the `hypoxia` geneList1 as an input I do not receive the same error message.. 

Thank You

**Comment by rbenel** [comment]
Hi, 

Any update?

Thanks

**Comment by s-aibar** [comment]
Dear @rbenel ,

Can you confirm whether the genes in your list are indeed in the database?
e.g. : 

```
geneList <- Cluster[[4]]
intersect(geneList, colnames(motifRankings))

```

**Comment by rbenel** [comment]
I can try, but I did write this post 2 years ago so I'm not even sure I remember what I was referring to..

**Comment by FloodLin** [comment]
I have the same promblem.
`> head(intersect(geneList, colnames(motifRankings)))
[1] "Tsc22d3" "Gnas"    "Nphs2"   "Tcf21"   "H2-Q6"   "Prss23" `
`Error in .RcisTarget_calcAUC(geneSets = geneSets, rankings = rankings,  : 
  Fewer than 80% of the genes/features in the gene-sets are included in the rankings.Check wether the IDs in the 'rankings' (columns) and 'geneSets' match.`

**Comment by wasonl** [comment]
Hi, I have the same issue, how can i deal with?
` head(intersect(geneList1, colnames(motifRankings)))
[1] "CDKN1A" "NEAT1"  "GDF15"  "HMOX1"  "HSPA1B"Error in .RcisTarget_calcAUC(geneSets = geneSets, rankings = rankings,  : 
  Fewer than 80% of the genes/features in the gene-sets are included in the rankings.Check wether the IDs in the 'rankings' (columns) and 'geneSets' match.`
