### ISSUE TITLE
S4 object error

### ISSUE THREAD

**Issue by tantrev** [aertslab/RcisTarget#2]
Greetings,

I was trying to go through the tutorial and ran into this error with the latest RcisTarget codebase:

> Error in nrow(motifRankings@rankings) : 
>   trying to get slot "rankings" from an object (class "data.table") that is not an S4 object 

Should it be of any use, I was also using the example code below:
```
library(RcisTarget)
library(RcisTarget.mm9.motifDatabases)
geneSet1 <- c("Fos")
geneLists <- list(geneSetName=geneSet1)

data(mm9_10kbpAroundTss_motifRanking)
data(mm9_direct_motifAnnotation)

motifRankings <- mm9_10kbpAroundTss_motifRanking

motifEnrichmentTable_wGenes <- cisTarget(geneLists, 
                                         motifRankings,
                                         motifAnnot_direct=mm9_direct_motifAnnotation)
```

Any help would be more than appreciated. :)

**Comment by s-aibar** [comment]
Hello,

I was updating RcisTarget today & introduced that bug. I think now it should be corrected, can you check whether you are using the last version (updated about what ago).

There is also the chance that I forgot to push the last changes into github... I will check tomorrow.

Thank you for letting me know! (&For using RcisTarget... :))

**Comment by s-aibar** [comment]
Hello, 
The new version of RcisTarget (updated today) needs a new format for the databases. I'll post in a while how to convert them.
Sorry for not warning it in advance!

**Comment by tantrev** [comment]
No worries, thank you!  I was just fiddling around and got things to work in the interim by reverting to the previous commit with:

`install_github("aertslab/RcisTarget@8f0e8158396247e48d1e9eece66308ca1bba4ae3")`

I'll keep my fingers crossed for the new databases.  Thank you! 👍

**Comment by s-aibar** [comment]
Ok, great. That is probably the best for now. 

In case you finally need it... as temporary solution, you can convert the current databases with the following code (adapt according to the organism/distance around TSS):

```
library(RcisTarget.mm9.motifDatabases)
data(mm9_10kbpAroundTss_motifRanking) # Adapt database name

motifRankings <- rankingWrapper(rankings=mm9_10kbpAroundTss_motifRanking, 
          rowType="gene", colType="motif", org="mouse", genome="mm9", description="")
```
