### ISSUE TITLE
RcisTarget for Bulk-seq?

### ISSUE THREAD

**Issue by QianzhaoJ** [aertslab/RcisTarget#21]
Hi
   `RcisTarget` is a very useful software for transcription factor analysis!
   I found the input of `RcisTarget` is GeneList, so perhaps I can apply the software for DEGs in my bulk RNA-seq data? Can you give me some suggestions?

   Thanks in advance!

Best,
Qianzhao

**Comment by s-aibar** [comment]
RcisTarget can be used with any kind of gene or region set, it is not specific for single-cell data. You will just need to be mindful of what kind of input you provided, in order to do the right interpretation for the output...
