### ISSUE TITLE
Database for Drosophila

### ISSUE THREAD

**Issue by frankyan** [aertslab/RcisTarget#3]
Thanks for the R implementation of cisTarget. I need to use it on Drosophila genes. Is there the database for Drosophila? Or how can I build it by myself?

**Comment by s-aibar** [comment]
Hello,
At the moment we don't have Drosophila databases. They are on the To-do list (we also need them for some of our analyses), but it will probably take a few weeks/months until they are ready for release.

**Comment by frankyan** [comment]
Thank you. Hope to see it soon.

**Comment by frankyan** [comment]
@s-aibar I am glad that the database for fly can be [requested](https://gbiomed.kuleuven.be/english/research/50000622/lcb/tools/scenic). How to request it? I didn't find contact information on that page. Thank you.
