### ISSUE TITLE
Cannot install RcisTarget!

### ISSUE THREAD

**Issue by saeedfc** [aertslab/RcisTarget#8]
Hi, 
I have pasted my console part below. I cannot install the package from bioconductor. 
I wanted to use scenic and went with this
`source("https://bioconductor.org/biocLite.R")`
biocLite(c("GENIE3", "RcisTarget", `"AUCell"))`

But it showed that rcistarget is not installed(other two packages were succesfully installed). So tried installing 'RcisTarget' individually.
`#installing` from bioconductor

`>` biocLite(pkgs = "RcisTarget")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.3 (2017-11-30).
Installing package(s) ‘RcisTarget’
Warning message:
package ‘RcisTarget’ is not available (for R version 3.4.3) 

#installing from file
`install.packages("~/R/RcisTarget_1.0.2.tar.gz")`
Warning` in install.packages :
  package` ‘~/R/RcisTarget_1.0.2.tar.gz’ is not available (for R version `3.4.3)`

Any idea what is going on here? Thank you very much for the help

**Comment by Ngort** [comment]
Same issue!

**Comment by s-aibar** [comment]
Hello,

to install it from file you need to set `repos=NULL` (otherwise it tries to find in in the remote repositories):
`install.packages("~/R/RcisTarget_1.0.2.tar.gz", repos=NULL)`

**Comment by ncedi12** [comment]
Hi there, I'm also struggling to install RcisTarget

I work with R/4.3.0 and biocManager version 3.18

your package seems to be configured to download with boconductor 3.18 but I get this error

package 'RcisTarget' is not available for Bioconductor version '3.18'

**Comment by XXiaoyueli** [comment]
> Hi there, I'm also struggling to install RcisTarget
> 
> I work with R/4.3.0 and biocManager version 3.18
> 
> your package seems to be configured to download with boconductor 3.18 but I get this error
> 
> package 'RcisTarget' is not available for Bioconductor version '3.18'

same issue

**Comment by XXiaoyueli** [comment]
> Hi there, I'm also struggling to install RcisTarget
> 
> I work with R/4.3.0 and biocManager version 3.18
> 
> your package seems to be configured to download with boconductor 3.18 but I get this error
> 
> package 'RcisTarget' is not available for Bioconductor version '3.18'

I tried these code and it works for me:
# Install remotes package if you haven't already
install.packages("remotes")

# Load the remotes package
library(remotes)

# Install RcisTarget from GitHub
remotes::install_github("aertslab/RcisTarget")
