### ISSUE TITLE
do.call need a list argument while RcisTarget uses unlist

### ISSUE THREAD

**Issue by zxystarrian** [aertslab/RcisTarget#9]
Hi there,

I was running RcisTarget through SCENIC package. But I got an error coming from RcisTarget function that at:
`aucMatrix <- do.call(rbind,
            unlist(aucMatrix, recursive = FALSE)[names(geneSets)])`
It said there's an error in do.call: second argument must be a list.
I wonder how can this work if do.call needs a list while there's an unlist in it?

Looking forward to your help. Thanks!

Best,
Xingyu

**Comment by danielee0707** [comment]
Same question here

**Comment by danielee0707** [comment]
I solved this by reducing the number of cores used. I guess it's a memory problem.

**Comment by s-aibar** [comment]
Hello,
This code needs an unlist to remove one level from the double-nested list returned by foreach. 
However, I have not been able to reproduce this error (not even adding too many cores, empty geneSets... etc). 
I have added an error handler that will save the internal data (for debugging) in case it happens again...
